escrm/urls.py
from django.urls import path
from . import views

app_name = 'escrm'

urlpatterns = [
    path('', views.CrmDashboard.as_view(), name='escrm-dashboard'),
    # dokumenty
    path('dokument/<int:pk>/', views.dokument_get, name='dokument-download'),
    path('dokument/<int:pk>/delete', views.DokumentDelete.as_view(), name='dokument-delete'),
    path('dokument/<int:pk>/add', views.dokument_add, name='dokument-add'),

    # Zarządzanie kontrahentami
    path('kontrahent/', views.KontrahentList.as_view(), name='kontrahent-list'),
    path('kontrahent/create/', views.KontrahentCreate.as_view(), name='kontrahent-create'),
    path('kontrahent/<int:pk>/', views.KontrahentDetail.as_view(), name='kontrahent-detail'),
    path('kontrahent/<int:pk>/update/', views.KontrahentUpdate.as_view(), name='kontrahent-update'),
    path('kontrahent/<int:pk>/delete/', views.KontrahentDelete.as_view(), name='kontrahent-delete'),
    path('kontrahent/<int:pk>/take/', views.kontrahent_take, name='kontrahent-take'),
    path('kontrahent/<int:pk>/dashboard/', views.kontrahent_dashboard, name='kontrahent-dashboard'),

    # Zarządzanie adresami
    path('kontrahent/set-default-adress/<int:pk>', views.default_check, name='default-check'),
    path('kontrahent/adres/create', views.adres_kontrahent_create, name='adres-kontrahent-create'),
    path('kontrahent/adres/update/get', views.adres_kontrahent_update, name='adres-kontrahent-update-get'),
    path('kontrahent/adres/<int:pk>/update/save', views.adres_kontrahent_update_saving, name='adres-kontrahent-update-save'),
    path('kontrahent/adres/<int:pk>/delete/', views.adres_kontrahent_delete, name='adres-kontrahent-delete'),

    # Zarządzanie osobami
    path('osoba/create/', views.osoba_create, name='osoba-create'),
    path('osoba/update/get', views.osoba_update, name='osoba-update-get'),
    path('osoba/<int:pk>/', views.OsobaDetail.as_view(), name='osoba-detail'),
    path('osoba/<int:pk>/update/save', views.osoba_update_saving, name='osoba-update-save'),
    path('osoba/<int:pk>/delete/', views.OsobaDelete.as_view(), name='osoba-delete'),

    # Zarządzanie adresami osób
    path('osoba/adres/create/', views.adres_osoba_create, name='adres-osoba-create'),
    path('osoba/adres/update/get', views.adres_osoba_update, name='adres-osoba-update-get'),
    path('osoba/adres/<int:pk>/update/save', views.adres_osoba_update_saving, name='adres-osoba-update-save'),
    path('osoba/adres/<int:pk>/delete', views.adres_osoba_delete, name='adres-osoba-delete'),

    # Zarządzanie zdarzeniami
    path('zdarzenie/', views.ZdarzenieList.as_view(), name='zdarzenie-list'),
    path('kontrahent/<int:pk>/zdarzenia/', views.ZdarzeniaDlaKontrahenta.as_view(), name='kontrahent-zdarzenia'),
    path('kontrahent/<int:pk>/zdarzenie/create/', views.ZdarzenieCreate.as_view(), name='zdarzenie-create'),
    path('zdarzenie/create/', views.ZdarzenieCreate.as_view(), name='zdarzenie-create'),
    path('zdarzenie/<int:pk>/', views.ZdarzenieDetail.as_view(), name='zdarzenie-detail'),
    path('zdarzenie/<int:pk>/update/', views.ZdarzenieUpdate.as_view(), name='zdarzenie-update'),
    path('zdarzenie/<int:pk>/delete/', views.ZdarzenieDelete.as_view(), name='zdarzenie-delete'),

    # produkty
    path('produkty/', views.ProduktyList.as_view(), name='produkty-list'),

    # oferty
    path('kontrahent/<int:pk>/oferty/', views.OfertyDlaKontrahenta.as_view(), name='kontrahent-oferty'),
    path('kontrahent/<int:pk>/oferty/create', views.OfertaCreate.as_view(), name='oferta-create'),
    path('kontrahent/<int:pk>/oferty/<int:pk_oferty>/update/', views.OfertaUpdate.as_view(),
        name='oferta-update'),
    path('kontrahent/<int:pk>/oferty/<int:pk_oferty>/', views.OfertaDetail.as_view(), name='oferta-detail'),
    path('kontrahent/<int:pk>/oferty/delete', views.OfertaDelete.as_view(), name='oferta-delete'),

    # umowy
    path('kontrahent/<int:pk>/umowy/', views.UmowyDlaKontrahenta.as_view(), name='kontrahent-umowy'),
    path('kontrahent/<int:pk>/umowy/create', views.UmowaCreate.as_view(), name='umowa-create'),
    path('kontrahent/<int:pk>/umowy/<int:pk_umowy>/update/', views.UmowaUpdate.as_view(), name='umowa-update'),
    # np. kontrahent/7/umowy/14
    path('kontrahent/<int:pk>/umowy/<int:pk_umowy>/', views.UmowaDetail.as_view(), name='umowa-detail'),
    path('kontrahent/<int:pk>/umowy/delete', views.UmowaDelete.as_view(), name='umowa-delete'),
    path('kontrahent/<int:pk>/umowy/valid', views.umowa_valid, name='umowa-valid'),

    # widoki dla opiekuna
    path('moi-klienci/', views.OpiekunKlienci.as_view(), name='opiekun-klienci-list'),
    path('moje-umowy/', views.OpiekunUmowy.as_view(), name='opiekun-umowy-list'),
    path('moje-zdarzenia/', views.OpiekunZdarzenia.as_view(), name='opiekun-zdarzenia-list'),
    path('moje-oferty/', views.OpiekunOferty.as_view(), name='opiekun-oferty-list'),

    # Edycja wybranej płatności np.
    # platnosc/47/update
    path('platnosc/<int:pk>/update', views.PlatnoscUpdate.as_view(), name='platnosc-update')
]

esdjango/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('password_reset/', views.reset_denied),
    # url(r'^password_reset/done/$', views.reset_denied),
    path('reset/', views.reset_denied),
    # url(r'^reset/done/$', views.reset_denied),
    path('password_change/', views.change_password),
    path('', include('django.contrib.auth.urls')),
    path('escrm/', include('escrm.urls')),
    path('admin/', admin.site.urls),
    path('accounts/profile/', views.cust_login),
    path('platnosci/', include('platnosci.urls')),
    path('korespondencja/', include('korespondencja.urls')),
    path('profil/', views.profil, name='profil'),
    path('profil/edit/', views.update_profile, name='profil-edit'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

escrm/models.py
from __future__ import unicode_literals

import os
from datetime import date

from django.contrib.auth.models import User
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.http import HttpResponseRedirect
from django.urls import reverse


class Profil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    telefon = models.CharField(max_length=15, blank=True)
    stanowisko = models.CharField(max_length=100, blank=True)

    # Methods
    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name

    def is_opiekun_of(self, kontrahent):
        return kontrahent.opiekun == self


class Kontrahent(models.Model):
    # Fields
    id_kontrahenta = models.AutoField(primary_key=True)
    nazwa_krotka = models.CharField(max_length=50, verbose_name="Nazwa krótka")
    nazwa_dluga = models.CharField(max_length=255, verbose_name="Pełna nazwa")
    nip = models.CharField(max_length=10)
    opiekun = models.ForeignKey(Profil, null=True, blank=True, on_delete=models.SET_NULL)
    czy_aktywny = models.BooleanField(default=False)
    email = models.CharField(null=True, blank=True, max_length=255)
    telefon = models.CharField(null=True, blank=True, max_length=45)
    notatka = models.TextField(null=True, blank=True)

    # Methods
    def __str__(self):
        return self.nazwa_krotka

    def get_absolute_url(self):
        return reverse('escrm:kontrahent-detail', kwargs={'pk': self.pk})

    def get_last_oferty(self, last):
        return self.oferta_set.all().order_by('-data_sporzadzenia')[:last]


class TypAdresu(models.Model):
    id = models.AutoField(primary_key=True)
    nazwa = models.CharField(max_length=60, null=False, blank=False)

    # Methods
    def __str__(self):
        return self.nazwa


class AdresKontrahent(models.Model):
    id_adresu = models.AutoField(primary_key=True)
    miasto = models.CharField(max_length=45)
    kod_pocztowy = models.CharField(max_length=6)
    ulica = models.CharField(max_length=45)
    kontrahent = models.ForeignKey(Kontrahent, on_delete=models.CASCADE)
    czy_domyslny = models.BooleanField(default=False)
    typ_adresu = models.ForeignKey(TypAdresu, null=False, blank=False, on_delete=models.PROTECT, default=1)

    def __str__(self):
        return self.ulica + ', ' + self.miasto


@receiver(pre_save, sender=AdresKontrahent)
def change_default_kontrahent_adres(sender, instance, **kwargs):
    if instance.czy_domyslny:
        adresy = AdresKontrahent.objects.filter(kontrahent=instance.kontrahent)
        adresy.update(czy_domyslny=False)
        instance.czy_domyslny = True


class Osoba(models.Model):
    id_osoby = models.AutoField(primary_key=True)
    imie = models.CharField(max_length=60, verbose_name="Imię")
    nazwisko = models.CharField(max_length=60)
    stanowisko = models.CharField(max_length=100)
    notatka = models.TextField(null=True)
    kontrahent = models.ManyToManyField(Kontrahent)

    def __str__(self):
        return self.imie + ' ' + self.nazwisko

    def get_absolute_url(self):
        return reverse('escrm:osoba-detail', kwargs={'pk': self.pk})


class AdresOsoba(models.Model):
    id_adresu = models.AutoField(primary_key=True)
    email = models.CharField(max_length=255)
    telefon = models.CharField(max_length=20)
    osoba = models.ForeignKey(Osoba, on_delete=models.CASCADE)
    czy_domyslny = models.BooleanField(default=False)


class TypZdarzenia(models.Model):
    id_typu = models.AutoField(primary_key=True)
    nazwa_zdarzenia = models.CharField(max_length=45)

    # Methods
    def __str__(self):
        return self.nazwa_zdarzenia


class Zdarzenie(models.Model):
    id_zdarzenia = models.AutoField(primary_key=True)
    data_zdarzenia = models.DateTimeField(auto_now=False, auto_now_add=False)
    temat = models.CharField(max_length=255)
    typ = models.ForeignKey(TypZdarzenia, on_delete=models.PROTECT)
    uzytkownik = models.ForeignKey(Profil, on_delete=models.PROTECT)
    kontrahent = models.ForeignKey(Kontrahent, on_delete=models.PROTECT)
    notatka = models.TextField()


class StatusOferty(models.Model):
    id_statusu_oferty = models.AutoField(primary_key=True)
    nazwa_statusu = models.CharField(max_length=45)

    def __str__(self):
        return self.nazwa_statusu


class Oferta(models.Model):
    id_oferty = models.AutoField(primary_key=True)
    temat = models.CharField(max_length=255)
    produkt = models.CharField(max_length=255)
    kontrahent = models.ForeignKey(Kontrahent, on_delete=models.PROTECT, db_column="kontrahent")
    termin_waznosci = models.DateField(auto_now=False, auto_now_add=False, verbose_name='Termin ważności')
    wartosc = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Wartość')
    status = models.ForeignKey(StatusOferty, null=True, on_delete=models.SET_NULL)
    akceptacja = models.BooleanField(default=False)
    data_sporzadzenia = models.DateField(auto_now=False, auto_now_add=False, verbose_name='Data sporządzenia')
    waluta = models.CharField(max_length=3, default='PLN')
    opiekun = models.ForeignKey(Profil, null=True, blank=True, on_delete=models.PROTECT)
    oferta_rodzic = models.ForeignKey('self', null=True, blank=True, on_delete=models.PROTECT)

    # prawdopodobnie do usunięcia
    @property
    def is_owner_of(self, profil):
        return True if self.opiekun == profil else False


class StatusUmowy(models.Model):
    id_statusu = models.AutoField(primary_key=True)
    nazwa = models.CharField(max_length=45)

    # Methods
    def __str__(self):
        return self.nazwa


class Umowa(models.Model):
    id_umowy = models.AutoField(primary_key=True)
    temat = models.CharField(max_length=255)
    produkt = models.CharField(max_length=255)
    termin_waznosci = models.DateField(null=True, auto_now=False, auto_now_add=False, verbose_name='Termin ważności')
    data_platnosci = models.DateField(null=True, auto_now=False, auto_now_add=False, verbose_name='Data płatności')
    data_sporzadzenia = models.DateField(auto_now=False, auto_now_add=False, verbose_name='Data sporządzenia')
    termin_platnosci = models.IntegerField(verbose_name='Termin płatności')
    waluta = models.CharField(max_length=3)
    kontrahent = models.ForeignKey(Kontrahent, on_delete=models.PROTECT)
    status = models.ForeignKey(StatusUmowy, null=True, on_delete=models.SET_NULL)
    wartosc = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Wartość')
    opiekun = models.ForeignKey(Profil, null=True, blank=True, on_delete=models.PROTECT)

    def how_much_progress(self):
        pass

    def __str__(self):
        return ' Do: ' + self.termin_waznosci.strftime('%m/%d/%Y') + ', ' + self.temat


def set_upload_path(instance, filename):
    rok = date.today().year
    miesiac = date.today().month
    if instance.umowa is not None:
        return 'umowy/{0}/{1}/{2}'.format(rok, miesiac, filename)
    elif instance.oferta is not None:
        return 'oferty/{0}/{1}/{2}'.format(rok, miesiac, filename)


class Dokument(models.Model):
    prefix = ''
    id_dokumentu = models.AutoField(primary_key=True)
    tytul_dokumentu = models.CharField(max_length=255, verbose_name='Tytuł dokumentu')
    nazwa_pliku = models.FileField(max_length=255, upload_to=set_upload_path)
    data_dodania = models.DateTimeField(auto_now=False, auto_now_add=True)
    umowa = models.ForeignKey(Umowa, null=True, on_delete=models.PROTECT)
    oferta = models.ForeignKey(Oferta, null=True, on_delete=models.PROTECT)
    uzytkownik = models.ForeignKey(Profil, on_delete=models.PROTECT)


@receiver(models.signals.post_delete, sender=Dokument)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Usuwa pliki z systemu plików gdy obiekt Dokument jest usuwany
    """
    if instance.nazwa_pliku:
        if os.path.isfile(instance.nazwa_pliku.path):
            os.remove(instance.nazwa_pliku.path)


class Platnosc(models.Model):
    id_platnosci = models.AutoField(primary_key=True)
    termin = models.DateField(auto_now=False, auto_now_add=False)
    kwota = models.DecimalField(max_digits=10, decimal_places=2)
    umowa = models.ForeignKey(Umowa, on_delete=models.PROTECT)
    kwota_zaksiegowana = models.DecimalField(max_digits=10, decimal_places=2)

    def is_done(self):
        return not self.kwota > self.kwota_zaksiegowana

    def is_delayed(self):
        return date.today() > self.termin and self.kwota > self.kwota_zaksiegowana

    def how_many_days_left(self):
        time_delta = self.termin - date.today()
        return ('{value} {end}'.format(value=time_delta.days, end='dni'))

    def __str__(self):
        return 'Platność dla: ' + self.umowa.kontrahent.nazwa_krotka + \
            ', o wartości: ' + str(self.kwota) + str(self.umowa.waluta) + \
            ', płatna do: ' + str(self.termin)


class AdresatNadawca(models.Model):
    id_adresata_nadawcy = models.AutoField(primary_key=True)
    nazwa = models.CharField(max_length=255, unique=True)
    miasto = models.CharField(max_length=255)
    kod_pocztowy = models.CharField(max_length=6)
    ulica = models.CharField(max_length=255)

    def __str__(self):
        return self.nazwa

    def get_absolute_url(self):
        return reverse('korespondencja:kontakt-list')


class Korespondencja(models.Model):
    RODZAJ = (('Wychodząca', 'Wychodząca'), ('Przychodząca', 'Przychodząca'))

    id_korespondencji = models.AutoField(primary_key=True)
    numer_korespondencji = models.CharField(max_length=60, null=True, blank=True)
    temat = models.CharField(max_length=255)
    data_dodania = models.DateTimeField(auto_now=False, auto_now_add=True)
    data_przyjscia_wyjscia = models.DateField(auto_now=False, auto_now_add=False)
    rodzaj = models.CharField(max_length=255, choices=RODZAJ, default=RODZAJ[1])

escrm/templates/escrm/adresy/kontrahentadres_form_modal.html
{% load widget_tweaks %}

<div class="modal-header">
  <h5 class="modal-title" id="lista_kontrahentow_modal_tytul">
    {% if role == 'update' %}
      Edytuj adres: {{ object.nazwa_dluga }}
    {% else %}
      Dodaj adres:
    {% endif %}
  </h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">
  <form action="/" method="post"
         {% if role == 'update' %}
              id="update-adres-form"
              data-url="{% url 'escrm:adres-kontrahent-update-save' pk %}"
          {% else %}
              id="create-adres-form"
              data-url="{% url 'escrm:adres-kontrahent-create' %}"
          {% endif %}>
    {% csrf_token %}
    {% for hidden in form_adres.hidden_fields %}
      {{ hidden }}
    {% endfor %}
    {{ form_adres.kontrahent }}

    {% for field in form_adres.visible_fields %}
      <div class="form-group">
      <label for="{{ field.id_for_label }}" class="col-form-label">{{ field.label }}:</label>
      {% if form_adres.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="col-sm-4"></div>
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
      </div>
    {% endfor %}
  </form>
</div>

<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Zamknij</button>
  <button type="button" class="btn btn-info"
      {% if role == 'update' %}
          id="js-submit-update-adres"
      {% else %}
          id="js-submit-create-adres"
      {% endif %}
  >Zapisz</button>
</div>

escrm/templates/escrm/adresy/kontrahentadres_list_modal.html
<div class="modal-header">
  <h5 class="modal-title" id="lista_kontrahentow_modal_tytul">
    Lista adresów: {{ object.nazwa_dluga }}
  </h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>#</th>
        <th>Ulica</th>
        <th>Kod</th>
        <th>Miasto</th>
        <th>Edycja</th>
      </tr>
    </thead>
    <tbody>
    {% for adres in object.adreskontrahent_set.all %}
      <tr id="tr_{{ adres.pk }}">
        <th>{{ forloop.counter }}</th>
        <td>{{ adres.ulica }}</td>
        <td>{{ adres.kod_pocztowy }}</td>
        <td>{{ adres.miasto }}</td>
        <td>
          <a class="btn btn-link btn-sm js-get-update-adres"
             href="#"
             id="{{ adres.pk }}"
             title="Edytuj"
             data-url="{% url 'escrm:adres-kontrahent-update-get' %}"
             data-toggle="tooltip"
             data-placement="bottom"
             data-trigger="hover">
            <i class="fas fa-edit"></i>
          </a>
          <form data-pk="{{ adres.pk }}" data-url="{% url 'escrm:adres-kontrahent-delete' adres.pk %}" method="post" class="form-inline" id="delete-adres">
          {% csrf_token %}
            <button
                type="button"
                class="btn btn-link btn-sm confirm3 js-submit-delete-adres"
                style="cursor:pointer"
                title="Usuń"
                data-toggle="tooltip"
                data-placement="bottom"
                data-trigger="hover">
              <i class="far fa-trash-alt"></i>
            </button>
            <label class="custom-control custom-checkbox"
                   title="Domyślny"
                   data-toggle="tooltip"
                   data-placement="bottom"
                   data-trigger="hover"
                   style="cursor:pointer">
              <input type="checkbox" data-pk="{{ adres.pk }}" class="custom-control-input default-chceck"
              {% if adres.czy_domyslny is True %} checked {% endif %}>
              <span class="custom-control-indicator"></span>
            </label>
          </form>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Zamknij</button>
</div>

escrm/templates/escrm/adresy/osobaadres_form_modal.html
{% load widget_tweaks %}

<div class="modal-header">
  <h5 class="modal-title" id="">
    {% if role == 'update' %}
      Edytuj adres: {{ object.imie }} {{ object.nazwisko }}
    {% else %}
      Dodaj adres:
    {% endif %}
  </h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">
  <form action="/" method="post"
         {% if role == 'update' %}
              id="update-adres-form"
              data-url="{% url 'escrm:adres-osoba-update-save' object.pk %}"
          {% else %}
              id="create-adres-form"
              data-url="{% url 'escrm:adres-osoba-create' %}"
          {% endif %}>
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}
    {{ form.osoba }}
    {% for field in form.visible_fields %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}" class="col-form-label">{{ field.label }}:</label>
        {% if form.is_bound %}
          {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
              <div class="col-sm-3"></div>
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
            {% render_field field class="form-control is-valid" %}
          {% endif %}
        {% else %}
          {% render_field field class="form-control" %}
        {% endif %}

        {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
      </div>
    {% endfor %}
  </form>
</div>

<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Zamknij</button>
  <button type="button" class="btn btn-info"
      {% if role == 'update' %}
          id="js-submit-update-adres"
      {% else %}
          id="js-submit-create-adres"
      {% endif %}
  >Zapisz</button>
</div>

escrm/templates/escrm/adresy/osobaadres_table.html
{% for adres in osoba.adresosoba_set.all %}
  <tr id="tr_{{ adres.pk }}">
    <td>{{ adres.email }}</td>
    <td>{{ adres.telefon }}</td>
    <td>
      <a href="#" class="btn btn-link btn-sm edit-buttons js-update-osoba-adres"
         data-pk="{{ adres.pk }}" data-url="{% url 'escrm:adres-osoba-update-get' %}">
        <i class="fas fa-edit"></i>
      </a>
      <form action="" method="post" class="form-inline" id="osoba-adres-delete-form">
        {% csrf_token %}
        <a data-url="{% url 'escrm:adres-osoba-delete' adres.pk %}" data-pk="{{ adres.pk }}" href="#"
                class="btn btn-link btn-sm confirm2 edit-buttons js-delete-osoba-adres" style="cursor:pointer">
          <i class="far fa-trash-alt"></i>
        </a>
      </form>
    </td>
  </tr>
{% endfor %}